{
 "title": "Water consumption bars",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Total stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current COLD water meter readings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT DATE, VALUE FROM WATER WHERE TYPE=1",
     "rawQueryText": "SELECT DATE, VALUE FROM WATER WHERE TYPE=1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current HOT water meter readings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT DATE, VALUE FROM WATER WHERE TYPE=2",
     "rawQueryText": "SELECT DATE, VALUE FROM WATER WHERE TYPE=2",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last week cold water consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS COLD\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/86400000 AS INT)\nHAVING UNIX_DATE >= ($__to-604800000) AND UNIX_DATE <= $__to;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS COLD\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/86400000 AS INT)\nHAVING UNIX_DATE >= ($__to-604800000) AND UNIX_DATE <= $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last week proportion",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS COLD\nFROM WATER_COLD\n-- GROUP BY CAST(UNIX_DATE/86400000 AS INT)\n--HAVING\nWHERE UNIX_DATE >= ($__to-604800000) AND UNIX_DATE <= $__to;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS COLD\nFROM WATER_COLD\n-- GROUP BY CAST(UNIX_DATE/86400000 AS INT)\n--HAVING\nWHERE UNIX_DATE >= ($__to-604800000) AND UNIX_DATE <= $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS HOT\nFROM WATER_COLD\n-- GROUP BY CAST(UNIX_DATE/86400000 AS INT)\n--HAVING\nWHERE UNIX_DATE >= ($__to-604800000) AND UNIX_DATE <= $__to;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS HOT\nFROM WATER_COLD\n-- GROUP BY CAST(UNIX_DATE/86400000 AS INT)\n--HAVING\nWHERE UNIX_DATE >= ($__to-604800000) AND UNIX_DATE <= $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last week hot water consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS HOT\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/86400000 AS INT)\nHAVING UNIX_DATE >= ($__to-604800000) AND UNIX_DATE <= $__to;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS HOT\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/86400000 AS INT)\nHAVING UNIX_DATE >= ($__to-604800000) AND UNIX_DATE <= $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last month cold water consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS COLD\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/86400000 AS INT)\nHAVING UNIX_DATE >= ($__to-2592000000) AND UNIX_DATE <= $__to;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS COLD\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/86400000 AS INT)\nHAVING UNIX_DATE >= ($__to-2592000000) AND UNIX_DATE <= $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last month hot water consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS HOT\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/86400000 AS INT)\nHAVING UNIX_DATE >= ($__to-2592000000) AND UNIX_DATE <= $__to;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT strftime('%d-%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS HOT\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/86400000 AS INT)\nHAVING UNIX_DATE >= ($__to-2592000000) AND UNIX_DATE <= $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last 6 months cold water consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT strftime('%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS COLD\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/2635200000 AS INT)\nHAVING UNIX_DATE >= ($__to-15811200000) AND UNIX_DATE <= $__to;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT strftime('%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS COLD\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/2635200000 AS INT)\nHAVING UNIX_DATE >= ($__to-15811200000) AND UNIX_DATE <= $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last 6 months hot water consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT strftime('%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS COLD\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/2635200000 AS INT)\nHAVING UNIX_DATE >= ($__to-15811200000) AND UNIX_DATE <= $__to;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT strftime('%m', DATE) AS DATE, 1000 * strftime('%s', DATE)-10800 as UNIX_DATE, VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT DATE, (MAX(VALUE)-MIN(VALUE)) AS COLD\nFROM WATER_COLD GROUP BY CAST(UNIX_DATE/2635200000 AS INT)\nHAVING UNIX_DATE >= ($__to-15811200000) AND UNIX_DATE <= $__to;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Manual range stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true
  },
  {
   "title": "Water delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT DATE, strftime('%s', DATE)-10800 as UNIX_DATE, TYPE, VALUE, IFNULL(LAG(VALUE) OVER (), VALUE) AS LAST_VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT UNIX_DATE, (VALUE-LAST_VALUE) AS Cold\nFROM WATER_COLD\n-- WHERE UNIX_DATE >= $__from AND UNIX_DATE <= $__to;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT DATE, strftime('%s', DATE)-10800 as UNIX_DATE, TYPE, VALUE, IFNULL(LAG(VALUE) OVER (), VALUE) AS LAST_VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT UNIX_DATE, (VALUE-LAST_VALUE) AS Cold\nFROM WATER_COLD\n-- WHERE UNIX_DATE >= $__from AND UNIX_DATE <= $__to;",
     "timeColumns": [
      "time",
      "ts",
      "UNIX_DATE"
     ]
    },
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT DATE, strftime('%s', DATE)-10800 as UNIX_DATE, TYPE, VALUE, IFNULL(LAG(VALUE) OVER (), VALUE) AS LAST_VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT UNIX_DATE, (VALUE-LAST_VALUE) AS Hot\nFROM WATER_COLD\n-- WHERE UNIX_DATE >= $__from AND UNIX_DATE <= $__to;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT DATE, strftime('%s', DATE)-10800 as UNIX_DATE, TYPE, VALUE, IFNULL(LAG(VALUE) OVER (), VALUE) AS LAST_VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT UNIX_DATE, (VALUE-LAST_VALUE) AS Hot\nFROM WATER_COLD\n-- WHERE UNIX_DATE >= $__from AND UNIX_DATE <= $__to;",
     "timeColumns": [
      "time",
      "ts",
      "UNIX_DATE"
     ]
    }
   ]
  },
  {
   "title": "Water consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "queryText": "WITH WATER_COLD AS (\n    SELECT DATE, strftime('%s', DATE)-10800 as UNIX_DATE, TYPE, VALUE, IFNULL(LAG(VALUE) OVER (), VALUE) AS LAST_VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT UNIX_DATE, (VALUE-LAST_VALUE) AS COLD\nFROM WATER_COLD\n-- WHERE UNIX_DATE >= $__from / 1000 AND UNIX_DATE <= $__to / 1000\nORDER BY UNIX_DATE ASC;",
     "rawQueryText": "WITH WATER_COLD AS (\n    SELECT DATE, strftime('%s', DATE)-10800 as UNIX_DATE, TYPE, VALUE, IFNULL(LAG(VALUE) OVER (), VALUE) AS LAST_VALUE\n    FROM WATER WHERE TYPE=1 ORDER BY DATE ASC\n)\nSELECT UNIX_DATE, (VALUE-LAST_VALUE) AS COLD\nFROM WATER_COLD\n-- WHERE UNIX_DATE >= $__from / 1000 AND UNIX_DATE <= $__to / 1000\nORDER BY UNIX_DATE ASC;",
     "timeColumns": [
      "time",
      "ts",
      "UNIX_DATE"
     ]
    },
    {
     "queryText": "WITH WATER_HOT AS (\n    SELECT DATE, strftime('%s', DATE)-10800 as UNIX_DATE, TYPE, VALUE, IFNULL(LAG(VALUE) OVER (), VALUE) AS LAST_VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT UNIX_DATE, (VALUE-LAST_VALUE) AS HOT\nFROM WATER_HOT\n-- WHERE UNIX_DATE >= $__from / 1000 AND UNIX_DATE <= $__to / 1000\nORDER BY UNIX_DATE ASC;",
     "rawQueryText": "WITH WATER_HOT AS (\n    SELECT DATE, strftime('%s', DATE)-10800 as UNIX_DATE, TYPE, VALUE, IFNULL(LAG(VALUE) OVER (), VALUE) AS LAST_VALUE\n    FROM WATER WHERE TYPE=2 ORDER BY DATE ASC\n)\nSELECT UNIX_DATE, (VALUE-LAST_VALUE) AS HOT\nFROM WATER_HOT\n-- WHERE UNIX_DATE >= $__from / 1000 AND UNIX_DATE <= $__to / 1000\nORDER BY UNIX_DATE ASC;",
     "timeColumns": [
      "time",
      "ts",
      "UNIX_DATE"
     ]
    }
   ]
  }
 ]
}